### ISSUE TITLE
code blocks show up wrong in todo mvc tutorial

### ISSUE THREAD

**Issue by catmando** [ruby-hyperloop/ruby-hyperloop.io#101]

**Comment by fzingg** [comment]
Talking about http://ruby-hyperloop.org/tutorials/hyperlooprails/todo-tutorial/ page ?
If yes, in which chapter ?

**Comment by catmando** [comment]
All of them :-)

**Comment by fzingg** [comment]
Not sure to get what you mean.

**Comment by catmando** [comment]
You know I guess its just in Chapter 2.  That chapter has several problems.  Now I see the rest is okay.  Sorry for the panic :-)
