### ISSUE TITLE
Opal links are incorrect

### ISSUE THREAD

**Issue by drhuffman12** [ruby-hyperloop/ruby-hyperloop.io#105]
Links to Opal pages from http://ruby-hyperloop.org/tutorials/opal/ (aka https://github.com/ruby-hyperloop/ruby-hyperloop.io/blob/master/tutorials/opal/index.html) are incorrect; they reference http://opalrb.org, but should reference http://opalrb.com.

**Comment by barriehadfield** [comment]
thank you for the PR, this is merged
