### ISSUE TITLE
Proposal for rewrite of Reactrb.org site

### ISSUE THREAD

**Issue by barriehadfield** [ruby-hyperloop/ruby-hyperloop.io#28]
Proposal to refactor reactrb.org as follows:
- The goal of this refactor is to reposition Reactrb as an umbrella project for Reactrb and associated Isomorphic ruby technologies
- The emphasis of the site will be to show how simple Reactrb is to use and also to show best practice for taking it further (Stores, etc). There will be a few tutorials.
- The new Reactrb.org will not try to mirroring the React(JS) site – but will have its own identity and structure but it will use as much of the existing Reactrb content as possible
- Remove all the original React(JS) text and structure (basically remove everything that comes from the original React site and does not pertain to Reactrb)
-   New fresh looking design
- The new site documentation will include Architectural and Pattern discussions, describing best practice when working with React like components and stores
-   Be inclusive of all Reactrb-family technologies including:
  - Reactrb (and the possible subdivision into Reactrb-dsl, etc)
  - Reactrb Router
  - Reactrb Reactive Record
  - Reactrb Synchromesh
  - Reactrb Hot-Reloader
  - Reactrb Express
- There will be a section on Reactrb development tools (Opal Console) and techniques
- All of the above Gem’s documentation should be on reactrb.org. The individual Gem’s Read-me’s should be minimal and refer to each Gem’s page on reactrb.org so we can emphasise that these gems are a part of the same family and explain how they work together
- Include installation, usage and best practice instructions for use with:
  - Rails
  - Sinatra
  - Webpack & NPM
- Will still include Live Ruby examples through Opal Playground
- The site will continue to be hosted on Github pages but the underlying technology will change to:
  - Reactrb Express
  - Middleman

**Comment by catmando** [comment]
that sounds really great!

An additional thought (just a thought that is all) is would there be an easy place to put user experience gist like posts.  We keep having short topics that people want to add... it would be nice to have someplace to put stuff like that without having to do a PR... or maybe not... maybe just make it obvious how to do a PR, and where the info could go.

**Comment by fkchang** [comment]
That looks great. I think putting all the info in one place will allow standardizing which of course will be useful. Once all the info is standardized, I would like to build tools to setup/config those standard practices very easily, both lowering the barrier to entry and just making it darn easy for those already using reactrb - I've some ideas.  Though I will say, I intend for this tooling to be opal wide, but will certainly support reactrb out of the box
