### ISSUE TITLE
Getting Started example throws exception

### ISSUE THREAD

**Issue by simplystuart** [ruby-hyperloop/ruby-hyperloop.io#32]
Example code on http://ruby-hyperloop.io/get_started/ throws undefined method exception for 'render'.

**Comment by catmando** [comment]
There is some version incompatibility going on here... I think react-express is on an older version.

Will just update per your PR as soon as @barriehadfield gets back...

Thanks again for the PR!

**Comment by simplystuart** [comment]
It works now! Thanks for updating.
