### ISSUE TITLE
Rename github repo from reactrb to hyperloop

### ISSUE THREAD

**Issue by barriehadfield** [ruby-hyperloop/ruby-hyperloop.io#36]
The Github repo is still https://github.com/reactrb which is inconsistent with the change to Hyperloop name. I would suggest us registering ruby-hyperloop and moving focus there (or renaming if that is possible)

@elia has suggested  github supports org and repo rename quite well, all checkouts and old links should keep working seamlessly

**Comment by zetachang** [comment]
Looks like we can directly change the org name (see https://help.github.com/articles/renaming-an-organization/) and the old link to repo will work but link to the org itself will result in 404 error.

**Comment by barriehadfield** [comment]
Good point. Could always create a new reactrb repo afterward with a simple readme redirecting to the newly renamed one. This would keep the exiting one working and not loose anyone looking for the old name.

**Comment by barriehadfield** [comment]
The org renaming plan is this:
1. Rename https://github.com/reactrb -> https://github.com/ruby-hyperloop.io
2. Rename https://github.com/reactrb2 -> https://github.com/reactrb

Anyone visiting https://github.com/reactrb should see https://github.com/reactrb2 which explains the rename and lets them find https://github.com/ruby-hyperloop.io

PLEASE READ THE FOLLOWING

Github Org rename details: https://help.github.com/articles/renaming-an-organization/

Those pushing updates to the repos must please read this: https://help.github.com/articles/changing-a-remote-s-url/

Additionally, external links to  https://github.com/reactrb need to be changed to https://github.com/ruby-hyperloop.io

I will do the website, but others need to please update external links they have control over.

**Comment by barriehadfield** [comment]
@zetachang, @catmando just making sure you see this: https://help.github.com/articles/changing-a-remote-s-url/

**Comment by elia** [comment]
> Good point. Could always create a new reactrb repo afterward with a simple readme redirecting to the newly renamed one. This would keep the exiting one working and not loose anyone looking for the old name.

@barriehadfield my advice is against renaming reactrb2 to reactrb as in that case you lose all the benefits of the github renaming support. Instead IMO you could just add a "Was looking for reactrb?" line at the top of the readme, and then remove it after sometime.

**Comment by barriehadfield** [comment]
Sorry @elia are you saying that the current Github auto-redirect will be lost if we add repos to the (new) reactrb one? 

For what I can see at the moment, everything seems to be working alright, you can push from an old reactrb repo to the newly renamed one with just a warning from Git, but the push works properly. Also the redirects are working properly - example: 
https://github.com/reactrb/reactrb.github.io/tree/source redirects properly to the renamed repo

I think that where this will stop working is if we actually use the new reactrb, which is not the intention. 

Let me know if I have misunderstood.

**Comment by zetachang** [comment]
Confirmed that the redirection still works, seems like it will only break if we reclaim the same name of old repo.

**Comment by elia** [comment]
> Confirmed that the redirection still works, seems like it will only break if we reclaim the same name of old repo.

Exactly, thanks @zetachang
