### ISSUE TITLE
Running in Production

### ISSUE THREAD

**Issue by barriehadfield** [ruby-hyperloop/ruby-hyperloop.io#39]
config.assets.js_compressor = Uglifier.new(compress: { drop_console: true })
this will cut out all console.log lines from assets
so that line above should go to production.rb in rails app
downside is that this cleans up all console commands at once
any console.info done at prod will be removed in assets compilation

**Comment by catmando** [comment]
so @noma4i has a PR on the generator to fix most of the issues as well.

The only other problem I encountered is not HyperLoop or Opal specific.  I have asked this question on SO: http://stackoverflow.com/questions/40937012/rails-config-assets-digest-defaulting-to-false-in-production

for now it would be good to add that to the doc as well even though its not Opal specific... (maybe rails 5 bug?)

**Comment by noma4i** [comment]
Sorry for delay. Will update generators to include that line as commented out.
