### ISSUE TITLE
Security certificate issue

### ISSUE THREAD

**Issue by stevensonmt** [ruby-hyperloop/ruby-hyperloop.io#44]
Had a hiccup with the chat app tutorial because chrome/vivaldi would not download the file 
`https://ruby-hyperloop.io/javascripts/test_chat_service.js` because it raised a security issue with the certificate not being verified.  Got around it by whitelisting the site, but should be avoided if possible.

**Comment by barriehadfield** [comment]
HTTPS is not supported by Github for custom domains https://help.github.com/articles/securing-your-github-pages-site-with-https/

@stevensonmt do you still get the same certificate issue using HTTP?
```
<script src="http://ruby-hyperloop.io/javascripts/test_chat_service.js"></script>
```

**Comment by catmando** [comment]
@stevensonmt thanks so much for pointing out these issues BTW!  Hope you are otherwise enjoying the tutorial

**Comment by stevensonmt** [comment]
Tutorial is great, thanks.  So I must have made the https error myself.  Thanks for pointing out the source of the issue.
