### ISSUE TITLE
New pages

### ISSUE THREAD

**Issue by barriehadfield** [ruby-hyperloop/ruby-hyperloop.io#48]
Proposal:

+ Rewrite 'Getting Started' as a first introduction to Hyperloop with extensive use of editable code snippets. The goal will be to give a first-time reader a full introduction and walk through of Components, Stores & Operations. This page will be written in friendly tutorial style encouraging experimentation in the editable code snippets. 
+ New page 'Architecture' will be a detailed overview of COMPS architecture and motivation. Text from Essays written previously. The style will be more formal and aimed at Rails developers branching out into front end technologies. Comparisons between other technologies and Hyperloop motivation explained. Architectural diagrams as necessary. 
+ Reformat 'Tutorials' page. Find a better layout which arranges tutorials by topic. 
+ Refactor 'Chat App Tutorial' to use editable code snippets so the whole tutorial can be completed without leaving the page.
+ Add HyperStore, HyperOperation and HyperSpec documentation to 'Docs' page

**Comment by catmando** [comment]
Looks really good

**Comment by barriehadfield** [comment]
All done
